language: python
env:
  - TOXENV=py27

install:
  - pip install tox

script:
  - tox

branches:
  only:
    - master

notifications:
  email:
    - gback@mitre.org
    - stix-commits-list@lists.mitre.org
